### ISSUE TITLE
Gli url del catalogo dovrebbero aprirsi in altra scheda

### ISSUE THREAD

**Issue by giuragu** [ondata/dpj#3]

**Comment by giuragu** [comment]
@aborruso come posso far aprire i link del catalogo su altra scheda? Non sembra bastare un semplice target="about_blank" :(

**Comment by aborruso** [comment]
Caro giu,  l'apertura del link è mediata da un javascript quindi era necessario aggiungere del codice in testa.

L'ho fatto ed è sotto. In ogni caso è `target="_blank"`.

Fai il refresh della pagina e se funziona chiudi la issue.

```javascript
<script>
var trackOutboundLink = function(url) {
   ga('send', 'event', 'outbound', 'click', url, {
     'transport': 'beacon',
     'hitCallback': function(){window.open(url, '_blank');}
   });
}
 </script>
```

**Comment by giuragu** [comment]
GRAZIE!!! :D
Così è molto meglio. Si naviga ma non si perde di vista il catalogo. Io farei sta modifica anche su petrusino e accussì. Casomai faccio io ok?

**Comment by aborruso** [comment]
@giuragu  per favore sì

**Comment by giuragu** [comment]
grazie ancora @aborruso. Ci penso io. Passo e chiudo
